<script setup lang="ts">
import { computed, ref } from 'vue'
import { useQuery, useQueryClient } from '@tanstack/vue-query'
import { BookmarkCheck, RefreshCw, Search, SlidersHorizontal, Sparkles } from '@lucide/vue'
import { api } from '../api/client'
import type { LibraryItem } from '../api/types'
import AppDialog from '../components/AppDialog.vue'
import PageHeader from '../components/PageHeader.vue'
import PosterCard from '../components/PosterCard.vue'
import StateBlock from '../components/StateBlock.vue'
import { useUIStore } from '../stores/ui'

const search=ref(''),status=ref('all'),ui=useUIStore(),qc=useQueryClient(),selected=ref<LibraryItem|null>(null),matchSource=ref('bangumi'),matchQuery=ref(''),matchResults=ref<Array<Record<string,unknown>>>([]),busy=ref(false)
const query=useQuery({queryKey:['library'],queryFn:()=>api<{items:LibraryItem[]}>('/library')})
const items=computed(()=>{const q=search.value.toLowerCase();return (query.data.value?.items||[]).filter(i=>(status.value==='all'||(status.value==='subscribed'&&i.is_subscribed)||(status.value==='local'&&i.is_local))&&`${i.title} ${i.title_cn} ${i.title_jp}`.toLowerCase().includes(q))})
async function refresh(){try{await api('/library/refresh',{method:'POST'});ui.toast('元数据刷新已经启动')}catch(e){ui.toast(e instanceof Error?e.message:'刷新失败','error')}}
async function refreshItem(){if(!selected.value)return;try{await api(`/library/metadata/${selected.value.ID}/refresh`,{method:'POST'});ui.toast('条目刷新已经启动')}catch(e){ui.toast(e instanceof Error?e.message:'刷新失败','error')}}
async function searchMatch(){if(!matchQuery.value.trim())return;busy.value=true;try{matchResults.value=await api<Array<Record<string,unknown>>>(`/metadata/search?q=${encodeURIComponent(matchQuery.value)}&source=${matchSource.value}`)}catch(e){ui.toast(e instanceof Error?e.message:'搜索失败','error')}finally{busy.value=false}}
async function fixMatch(item:Record<string,unknown>){if(!selected.value)return;try{await api('/library/fix-match',{method:'POST',body:JSON.stringify({id:selected.value.ID,type:'metadata',source:matchSource.value,source_id:Number(item.id||item.ID||0)}),headers:{'Content-Type':'application/json'}});ui.toast('匹配关系已更新');matchResults.value=[];qc.invalidateQueries({queryKey:['library']})}catch(e){ui.toast(e instanceof Error?e.message:'匹配失败','error')}}
async function setBangumi(statusValue:number){if(!selected.value?.bangumi_id)return;try{await api(`/bangumi/subject/${selected.value.bangumi_id}/collection`,{method:'POST',body:JSON.stringify({status:statusValue}),headers:{'Content-Type':'application/json'}});ui.toast('Bangumi 收藏状态已同步')}catch(e){ui.toast(e instanceof Error?e.message:'同步失败','error')}}
function open(item:LibraryItem){selected.value=item;matchQuery.value=item.title_cn||item.title;matchResults.value=[]}
const resultName=(item:Record<string,unknown>)=>String(item.name_cn||item.NameCN||item.name||item.Name||'未命名条目')
</script>

<template><div class="page-grid"><PageHeader eyebrow="COLLECTION" title="番剧图鉴" description="统一浏览订阅与本地媒体的元数据、海报和来源状态。"><button class="btn btn-primary" @click="refresh"><RefreshCw :size="17"/>刷新全部元数据</button></PageHeader><section class="panel grid gap-3 p-4 md:grid-cols-[1fr_auto]"><label class="relative"><Search class="muted absolute left-3 top-3" :size="18"/><input v-model="search" class="field pl-10" placeholder="搜索中、日、英文标题" aria-label="搜索番剧"/></label><div class="flex gap-2 overflow-x-auto"><button v-for="item in [{id:'all',label:'全部'},{id:'subscribed',label:'已订阅'},{id:'local',label:'本地可用'}]" :key="item.id" class="btn whitespace-nowrap" :class="status===item.id?'btn-primary':'btn-secondary'" @click="status=item.id"><SlidersHorizontal v-if="item.id==='all'" :size="15"/>{{ item.label }}</button></div></section><StateBlock v-if="query.isLoading.value" state="loading"/><StateBlock v-else-if="query.isError.value" state="error" title="图鉴加载失败" @retry="query.refetch()"/><StateBlock v-else-if="!items.length" state="empty" title="没有符合条件的番剧"/><section v-else class="poster-grid"><PosterCard v-for="item in items" :key="item.ID" :title="item.title_cn||item.title||item.title_jp||'未命名番剧'" :image="item.image" :meta="item.air_date||item.data_source" :badges="[item.is_subscribed?'已订阅':'',item.is_local?'本地可用':''].filter(Boolean)"><div class="mt-3 grid gap-2"><button class="btn btn-secondary w-full text-xs" @click="open(item)"><Sparkles :size="14"/>详情与匹配</button><RouterLink v-if="item.is_local" class="btn btn-quiet w-full text-xs" :to="`/local-anime?highlight=${item.local_anime_id}`">打开本地媒体</RouterLink></div></PosterCard></section>
  <AppDialog :open="Boolean(selected)" :title="selected?.title_cn||selected?.title||'番剧详情'" description="检查来源信息、修正匹配，并同步收藏状态。" wide @update:open="v=>{if(!v)selected=null}"><div class="grid gap-6 lg:grid-cols-[260px_1fr]"><section><img :src="selected?.image||'/static/img/no_poster.svg'" alt="" class="aspect-[2/3] w-full rounded-2xl object-cover"/><div class="mt-3 flex flex-wrap gap-2"><span class="badge">{{ selected?.data_source||'metadata' }}</span><span v-if="selected?.is_subscribed" class="badge badge-success">已订阅</span><span v-if="selected?.is_local" class="badge badge-success">本地可用</span></div><p class="muted mt-4 text-sm leading-6">{{ selected?.summary||'暂无简介' }}</p><button class="btn btn-secondary mt-4 w-full" @click="refreshItem"><RefreshCw :size="16"/>刷新此条目</button><div v-if="selected?.bangumi_id" class="panel-muted mt-4 p-3"><p class="text-xs font-black">Bangumi 收藏</p><div class="mt-2 grid grid-cols-2 gap-2"><button class="btn btn-quiet px-2 text-xs" @click="setBangumi(1)">想看</button><button class="btn btn-quiet px-2 text-xs" @click="setBangumi(3)"><BookmarkCheck :size="14"/>在看</button><button class="btn btn-quiet px-2 text-xs" @click="setBangumi(2)">看过</button><button class="btn btn-quiet px-2 text-xs" @click="setBangumi(4)">搁置</button></div></div></section><section><h3 class="text-lg font-black">手动修正匹配</h3><p class="muted mt-1 text-sm">选择数据源并搜索正确条目；修改会同步到关联的订阅与本地媒体。</p><div class="mt-4 grid gap-3 sm:grid-cols-[140px_1fr_auto]"><select v-model="matchSource" class="field"><option value="bangumi">Bangumi</option><option value="tmdb">TMDB</option><option value="anilist">AniList</option></select><input v-model="matchQuery" class="field" @keydown.enter.prevent="searchMatch"/><button class="btn btn-primary" :disabled="busy" @click="searchMatch"><Search :size="16"/>搜索</button></div><div class="mt-4 space-y-2"><button v-for="item in matchResults" :key="String(item.id||item.ID)" class="panel-muted flex min-h-16 w-full items-center justify-between gap-3 p-3 text-left" @click="fixMatch(item)"><span><strong>{{ resultName(item) }}</strong><small class="muted mt-1 block">#{{ item.id||item.ID }}</small></span><span class="badge badge-success">使用此匹配</span></button></div><StateBlock v-if="!matchResults.length" state="empty" title="搜索并选择正确条目"/></section></div></AppDialog>
</div></template>
