<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { useQuery, useQueryClient } from '@tanstack/vue-query'
import { CircleAlert, FolderCog, FolderPlus, Play, RefreshCw, Search, Sparkles, Trash2, WandSparkles } from '@lucide/vue'
import { api, handlePosterError, posterURL } from '../api/client'
import type { LocalAnime, TaskAccepted } from '../api/types'
import AppDialog from '../components/AppDialog.vue'
import AsyncButton from '../components/AsyncButton.vue'
import ConfirmDialog from '../components/ConfirmDialog.vue'
import PageHeader from '../components/PageHeader.vue'
import PosterCard from '../components/PosterCard.vue'
import StateBlock from '../components/StateBlock.vue'
import { useAsyncActions } from '../composables/useAsyncActions'
import { useUIStore } from '../stores/ui'

interface Directory { ID:number; path:string; description:string }
interface Issue { ID:number; Title?:string; title?:string; Message?:string; message?:string; Hint?:string; hint?:string }
interface Payload { directories:Directory[]; items:LocalAnime[]; scan_status:Record<string,unknown>; diagnostics:Issue[] }
interface RenameItem { anime_name:string; original:string; new:string; path:string }

const ui=useUIStore(),qc=useQueryClient(),actions=useAsyncActions(),search=ref(''),adding=ref(false),dirPath=ref(''),deleteDir=ref<Directory|null>(null),renameDir=ref<Directory|null>(null),renamePattern=ref('{Title} S{Season}E{Ep}'),renamePreview=ref<RenameItem[]>([]),selected=ref<LocalAnime|null>(null),matchQuery=ref(''),matchSource=ref('bangumi'),matchResults=ref<Array<Record<string,unknown>>>([])
const query=useQuery({queryKey:['local-anime'],queryFn:()=>api<Payload>('/local-anime')})
const items=computed(()=>{const q=search.value.toLowerCase();return(query.data.value?.items||[]).filter(i=>`${i.title} ${i.metadata?.title_cn||''}`.toLowerCase().includes(q))})
const visibleCount=ref(24)
const visibleItems=computed(()=>items.value.slice(0,visibleCount.value))
const canLoadMore=computed(()=>visibleItems.value.length<items.value.length)
watch(search,()=>{visibleCount.value=24})
async function scan(){try{await actions.runTask('scan',()=>api<TaskAccepted>('/local-anime/scan',{method:'POST'}),'本地扫描','scan','正在扫描本地媒体目录');ui.toast('本地扫描已经启动')}catch(e){ui.toast(e instanceof Error?e.message:'扫描失败','error')}}
async function chooseDir(){try{await actions.run('choose-dir',async()=>{const result=await api<{path:string}>('/system/pick-directory',{method:'POST',body:JSON.stringify({title:'选择媒体目录',default_path:dirPath.value}),headers:{'Content-Type':'application/json'}});if(result.path)dirPath.value=result.path})}catch(e){ui.toast(e instanceof Error?e.message:'目录选择不可用','error')}}
async function add(){try{await actions.runTask('add-dir',async()=>{const task=await api<TaskAccepted>('/local-directories',{method:'POST',body:JSON.stringify({path:dirPath.value}),headers:{'Content-Type':'application/json'}});dirPath.value='';adding.value=false;ui.toast('目录已添加，扫描已经启动');qc.invalidateQueries({queryKey:['local-anime']});return task},'本地扫描','scan','目录已添加，正在扫描本地媒体')}catch(e){ui.toast(e instanceof Error?e.message:'添加失败','error')}}
async function removeDir(){if(!deleteDir.value)return;const id=deleteDir.value.ID;try{await actions.run(`remove-${id}`,async()=>{await api(`/local-directories/${id}`,{method:'DELETE'});ui.toast('目录已移除；磁盘文件未被删除');deleteDir.value=null;qc.invalidateQueries({queryKey:['local-anime']})})}catch(e){ui.toast(e instanceof Error?e.message:'移除失败','error')}}
async function previewRename(){if(!renameDir.value)return;const id=renameDir.value.ID;try{await actions.run(`rename-preview-${id}`,async()=>{renamePreview.value=await api<RenameItem[]>(`/local-directories/${id}/rename-preview`,{method:'POST',body:JSON.stringify({pattern:renamePattern.value,season:'',is_manual:false}),headers:{'Content-Type':'application/json'}})})}catch(e){ui.toast(e instanceof Error?e.message:'预览失败','error')}}
async function applyRename(){if(!renameDir.value||!renamePreview.value.length)return;const id=renameDir.value.ID;try{await actions.run(`rename-apply-${id}`,async()=>{await api(`/local-directories/${id}/rename`,{method:'POST',body:JSON.stringify({pattern:renamePattern.value,season:'',is_manual:false}),headers:{'Content-Type':'application/json'}});ui.toast('重命名完成');renameDir.value=null;renamePreview.value=[];qc.invalidateQueries({queryKey:['local-anime']})})}catch(e){ui.toast(e instanceof Error?e.message:'重命名失败','error')}}
async function refreshMetadata(item:LocalAnime){try{await actions.runTask(`refresh-${item.ID}`,()=>api<TaskAccepted>(`/local-anime/${item.ID}/refresh-metadata`,{method:'POST'}),'刷新本地番剧元数据','metadata',`正在刷新 ${item.title}`);ui.toast('元数据刷新已经启动')}catch(e){ui.toast(e instanceof Error?e.message:'刷新失败','error')}}
async function switchSource(source:string){if(!selected.value)return;try{await actions.run(`source-${source}`,async()=>{await api(`/local-anime/${selected.value!.ID}/source?source=${source}`,{method:'POST'});ui.toast('显示数据源已切换');qc.invalidateQueries({queryKey:['local-anime']})})}catch(e){ui.toast(e instanceof Error?e.message:'切换失败','error')}}
async function searchMatch(){if(!matchQuery.value.trim())return;try{await actions.run('search-match',async()=>{matchResults.value=await api<Array<Record<string,unknown>>>(`/metadata/search?q=${encodeURIComponent(matchQuery.value)}&source=${matchSource.value}`)})}catch(e){ui.toast(e instanceof Error?e.message:'搜索失败','error')}}
async function fixMatch(result:Record<string,unknown>){if(!selected.value)return;const sourceID=Number(result.id||result.ID||0);try{await actions.run(`fix-${sourceID}`,async()=>{await api('/library/fix-match',{method:'POST',body:JSON.stringify({id:selected.value!.ID,type:'local',source:matchSource.value,source_id:sourceID}),headers:{'Content-Type':'application/json'}});ui.toast('匹配关系已更新');matchResults.value=[];qc.invalidateQueries({queryKey:['local-anime']})})}catch(e){ui.toast(e instanceof Error?e.message:'匹配失败','error')}}
const resultName=(item:Record<string,unknown>)=>String(item.name_cn||item.NameCN||item.name||item.Name||'未命名条目')
</script>

<template>
  <div class="page-grid">
    <PageHeader eyebrow="ON DEVICE" title="本地番剧" description="扫描本地媒体，检查元数据，并从同一工作区进入播放。"><button class="btn btn-secondary" @click="adding=true"><FolderPlus :size="17"/>添加目录</button><AsyncButton class="btn btn-primary" :loading="actions.isBusy('scan','local-scan')" loading-label="扫描中…" @click="scan"><RefreshCw :size="17"/>重新扫描</AsyncButton></PageHeader>
    <section v-if="query.data.value?.diagnostics.length" class="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-900 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-200"><div class="flex items-start gap-3"><CircleAlert class="shrink-0"/><div><strong>媒体库有 {{ query.data.value.diagnostics.length }} 项需要关注</strong><p class="mt-1 text-sm">{{ query.data.value.diagnostics[0].Title||query.data.value.diagnostics[0].title }}：{{ query.data.value.diagnostics[0].Message||query.data.value.diagnostics[0].message }}</p></div></div></section>
    <section class="panel p-4"><div class="grid gap-3 lg:grid-cols-[1fr_auto]"><label class="relative block"><Search class="muted absolute left-3 top-3" :size="18"/><input v-model="search" class="field pl-10" placeholder="搜索本地番剧" aria-label="搜索本地番剧"/></label><span class="badge self-center">{{ items.length }} 部本地番剧</span></div><div v-if="query.data.value?.directories.length" class="mt-4 grid gap-2 lg:grid-cols-2"><article v-for="dir in query.data.value.directories" :key="dir.ID" class="panel-muted flex min-w-0 items-center gap-3 p-3"><FolderCog class="shrink-0 text-[var(--sky)]" :size="19"/><div class="min-w-0 flex-1"><p class="truncate text-sm font-bold">{{ dir.path }}</p><p class="muted text-xs">扫描根目录</p></div><button class="btn btn-quiet h-11 w-11 p-0" aria-label="批量重命名" @click="renameDir=dir;renamePreview=[]"><WandSparkles :size="16"/></button><button class="btn btn-danger h-11 w-11 p-0" aria-label="移除目录" @click="deleteDir=dir"><Trash2 :size="16"/></button></article></div></section>
    <StateBlock v-if="query.isLoading.value" state="loading"/><StateBlock v-else-if="query.isError.value" state="error" title="本地媒体加载失败" :retrying="query.isFetching.value" @retry="query.refetch()"/><StateBlock v-else-if="!items.length" state="empty" title="还没有扫描到本地番剧" description="先添加包含番剧文件夹的根目录，然后运行一次扫描。"/>
    <section v-else class="poster-grid"><PosterCard v-for="item in visibleItems" :key="item.ID" :title="item.metadata?.title_cn||item.metadata?.title||item.title" :image="posterURL(item.metadata||{image:item.image},{width:360})" :meta="`${item.file_count} 集 · 第 ${item.season||1} 季`" :badges="item.has_repair_actions?['待完善']:[]"><div class="mt-3 grid gap-2"><RouterLink class="btn btn-primary w-full text-xs" :to="`/player?anime=${item.ID}`"><Play :size="14"/>查看与播放</RouterLink><button class="btn btn-secondary w-full text-xs" @click="selected=item;matchQuery=item.title"><Sparkles :size="14"/>元数据与匹配</button></div></PosterCard></section>
    <button v-if="canLoadMore" class="btn btn-secondary mx-auto" type="button" @click="visibleCount+=24">继续加载（{{ items.length-visibleItems.length }}）</button>

    <AppDialog :open="adding" title="添加媒体目录" description="目录会在后台扫描，不会移动已有文件。" @update:open="adding=$event"><form @submit.prevent="add"><label class="label">绝对路径<div class="flex gap-2"><input v-model="dirPath" class="field" placeholder="/Volumes/Anime" required/><AsyncButton class="btn btn-secondary shrink-0" :loading="actions.isBusy('choose-dir')" loading-label="选择中…" @click="chooseDir">选择</AsyncButton></div></label><div class="mt-6 flex justify-end"><AsyncButton type="submit" class="btn btn-primary" :loading="actions.isBusy('add-dir','local-scan')" loading-label="扫描中…">添加并扫描</AsyncButton></div></form></AppDialog>
    <AppDialog :open="Boolean(renameDir)" :title="`整理 ${renameDir?.path||''}`" description="先预览所有文件名；确认后才会更新磁盘文件与数据库记录。" wide @update:open="v=>{if(!v){renameDir=null;renamePreview=[]}}"><label class="label">命名模板<input v-model="renamePattern" class="field font-mono"/></label><div v-if="renamePreview.length" class="mt-5 max-h-80 space-y-2 overflow-y-auto"><div v-for="item in renamePreview" :key="item.path" class="panel-muted p-3 text-sm"><p class="muted line-through">{{ item.original }}</p><p class="mt-1 font-bold text-[var(--success)]">{{ item.new }}</p></div></div><p v-else class="panel-muted muted mt-5 p-5 text-center text-sm">生成预览后再确认重命名。</p><div class="mt-6 flex justify-end gap-2"><AsyncButton class="btn btn-secondary" :loading="Boolean(renameDir&&actions.isBusy(`rename-preview-${renameDir.ID}`))" loading-label="生成中…" @click="previewRename">生成预览</AsyncButton><AsyncButton class="btn btn-primary" :disabled="!renamePreview.length" :loading="Boolean(renameDir&&actions.isBusy(`rename-apply-${renameDir.ID}`))" loading-label="应用中…" @click="applyRename">应用 {{ renamePreview.length }} 项</AsyncButton></div></AppDialog>
    <AppDialog :open="Boolean(selected)" :title="selected?.metadata?.title_cn||selected?.title||'元数据'" description="刷新当前条目、切换显示源，或手动修正匹配。" wide @update:open="v=>{if(!v){selected=null;matchResults=[]}}"><div class="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><section class="panel-muted p-4"><img :src="posterURL(selected?.metadata||{image:selected?.image},{width:720})" alt="" decoding="async" class="mx-auto aspect-[2/3] w-full max-w-48 rounded-xl object-cover" @error="handlePosterError($event,selected?.image)"/><p class="muted mt-4 text-sm leading-6">{{ selected?.metadata?.summary||selected?.summary||'暂无简介' }}</p><AsyncButton class="btn btn-secondary mt-4 w-full" :loading="Boolean(selected&&actions.isBusy(`refresh-${selected.ID}`,`local-metadata-${selected.ID}`))" loading-label="刷新中…" @click="selected&&refreshMetadata(selected)"><RefreshCw :size="16"/>刷新元数据</AsyncButton><div class="mt-3 grid grid-cols-3 gap-2"><AsyncButton v-for="source in ['bangumi','tmdb','anilist']" :key="source" class="btn btn-quiet px-2 text-xs" :loading="actions.isBusy(`source-${source}`)" loading-label="切换中…" @click="switchSource(source)">{{ source }}</AsyncButton></div></section><section><div class="grid gap-3 sm:grid-cols-[140px_1fr_auto]"><select v-model="matchSource" class="field"><option value="bangumi">Bangumi</option><option value="tmdb">TMDB</option><option value="anilist">AniList</option></select><input v-model="matchQuery" class="field" placeholder="搜索标题" @keydown.enter.prevent="searchMatch"/><AsyncButton class="btn btn-primary" :loading="actions.isBusy('search-match')" loading-label="搜索中…" @click="searchMatch"><Search :size="16"/>搜索</AsyncButton></div><div class="mt-4 space-y-2"><AsyncButton v-for="item in matchResults" :key="String(item.id||item.ID)" class="panel-muted flex min-h-16 w-full items-center justify-between gap-3 p-3 text-left" :loading="actions.isBusy(`fix-${Number(item.id||item.ID||0)}`)" loading-label="正在应用匹配…" @click="fixMatch(item)"><span><strong>{{ resultName(item) }}</strong><small class="muted mt-1 block">#{{ item.id||item.ID }}</small></span><span class="badge badge-success">使用此匹配</span></AsyncButton></div><StateBlock v-if="!matchResults.length" state="empty" title="搜索并选择正确条目" description="手动匹配会同步更新订阅、本地库和 NFO 数据。"/></section></div></AppDialog>
    <ConfirmDialog :open="Boolean(deleteDir)" danger :loading="Boolean(deleteDir&&actions.isBusy(`remove-${deleteDir.ID}`))" loading-label="移除中…" title="移除扫描目录？" :description="`只会移除 ${deleteDir?.path||''} 的索引，不会删除磁盘上的媒体文件。`" confirm-label="移除目录" @update:open="v=>{if(!v)deleteDir=null}" @confirm="removeDir"/>
  </div>
</template>
