<script setup lang="ts">
import { ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ArrowRight, Eye, EyeOff, ShieldCheck, Sparkles } from '@lucide/vue'
import AsyncButton from '../components/AsyncButton.vue'
import { useSessionStore } from '../stores/session'

const session=useSessionStore(), router=useRouter(), route=useRoute()
const username=ref('admin'), password=ref(''), remember=ref(true), show=ref(false), busy=ref(false), error=ref('')
async function submit(){if(busy.value)return;busy.value=true;error.value='';try{const state=await session.login(username.value,password.value,remember.value);await router.push(state.setup_pending?'/setup':String(route.query.redirect||'/'))}catch(e){error.value=e instanceof Error?e.message:'登录失败'}finally{busy.value=false}}
</script>
<template><main class="app-backdrop grid min-h-screen place-items-center p-4"><div class="grid w-full max-w-5xl overflow-hidden rounded-[2rem] border border-[var(--line)] bg-[var(--surface-solid)] shadow-2xl md:grid-cols-[1.1fr_.9fr]"><section class="relative hidden min-h-[650px] overflow-hidden bg-gradient-to-br from-rose-100 via-pink-50 to-sky-100 p-12 text-slate-800 md:block"><div class="absolute -right-20 -top-20 h-72 w-72 rounded-full bg-white/60 blur-3xl"></div><div class="relative flex h-full flex-col"><div class="flex items-center gap-3"><span class="grid h-12 w-12 place-items-center rounded-2xl bg-rose-500 text-white shadow-lg"><Sparkles/></span><strong class="text-xl">AnimateTool</strong></div><div class="my-auto"><p class="eyebrow">YOUR ANIME COMMAND CENTER</p><h1 class="mt-4 max-w-lg text-5xl font-black leading-[1.08] tracking-[-.055em]">追番、下载、整理和播放，一切都恰到好处。</h1><p class="mt-6 max-w-md text-base leading-7 text-slate-600">一处看清今日更新、订阅状态和本地媒体，让自动化安静地完成剩下的事。</p></div><div class="flex items-center gap-2 text-sm font-bold text-slate-600"><ShieldCheck :size="18"/>所有数据留在你的设备上</div></div></section><section class="p-6 sm:p-10 md:p-12"><div class="mb-10 md:hidden"><span class="mb-4 grid h-12 w-12 place-items-center rounded-2xl bg-rose-500 text-white"><Sparkles/></span><strong class="text-xl">AnimateTool</strong></div><p class="eyebrow">欢迎回来</p><h2 class="page-title mt-2">登录媒体库</h2><p class="muted mt-2 text-sm">使用管理员账户继续管理你的追番自动化。</p><form class="mt-9 space-y-5" @submit.prevent="submit"><label class="label">用户名<input v-model="username" class="field" autocomplete="username" required/></label><label class="label">密码<div class="relative"><input v-model="password" class="field pr-12" :type="show?'text':'password'" autocomplete="current-password" required autofocus/><button class="absolute right-1 top-1 grid h-10 w-10 place-items-center rounded-lg muted" type="button" @click="show=!show" :aria-label="show?'隐藏密码':'显示密码'"><EyeOff v-if="show" :size="18"/><Eye v-else :size="18"/></button></div></label><div class="flex items-center justify-between gap-3 text-sm"><label class="flex items-center gap-2 font-bold"><input v-model="remember" type="checkbox" class="h-4 w-4 accent-[var(--brand)]"/>记住我</label><RouterLink to="/recover" class="font-bold text-[var(--brand)]">本机恢复</RouterLink></div><p v-if="error" role="alert" class="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700 dark:bg-red-950/40 dark:text-red-300">{{ error }}</p><AsyncButton type="submit" class="btn btn-primary w-full" :loading="busy" loading-label="正在登录…">进入 AnimateTool<ArrowRight :size="18"/></AsyncButton></form></section></div></main></template>
