<script setup lang="ts">
import { computed, reactive, ref, watchEffect } from 'vue'
import { useQuery, useQueryClient } from '@tanstack/vue-query'
import { Bot, Cloud, Database, Download, Film, KeyRound, Network, RefreshCw, Save, Settings2, ShieldCheck, Wrench } from '@lucide/vue'
import { api } from '../api/client'
import type { TaskAccepted } from '../api/types'
import AsyncButton from '../components/AsyncButton.vue'
import PageHeader from '../components/PageHeader.vue'
import StateBlock from '../components/StateBlock.vue'
import { useAsyncActions } from '../composables/useAsyncActions'
import { useUIStore, type ThemeMode } from '../stores/ui'

interface SettingsData{values:Record<string,string>;configured:Record<string,boolean>;stats:Record<string,unknown>}
interface Field { key:string; label:string; type?:'text'|'password'|'select'|'boolean'; options?:Array<{value:string;label:string}> }
interface Group { id:string;label:string;icon:unknown;fields:Field[];providers?:string[] }
interface AuditEntry { id:number;created_at:string;username:string;action:string;outcome:string;ip:string;target_type:string;target_id:string }
const groups:Group[]=[
  {id:'downloader',label:'下载器',icon:Download,providers:['qb'],fields:[{key:'qb_mode',label:'运行模式',type:'select',options:[{value:'managed',label:'内置托管'},{value:'external',label:'外部 Web UI'}]},{key:'qb_url',label:'Web UI 地址'},{key:'qb_username',label:'用户名'},{key:'qb_password',label:'密码',type:'password'},{key:'base_download_dir',label:'下载目录'}]},
  {id:'metadata',label:'元数据',icon:Database,providers:['bangumi','tmdb','anilist'],fields:[{key:'tmdb_token',label:'TMDB Token',type:'password'},{key:'anilist_token',label:'AniList Token',type:'password'},{key:'bangumi_app_id',label:'Bangumi App ID'},{key:'bangumi_app_secret',label:'Bangumi App Secret',type:'password'},{key:'bangumi_access_token',label:'Bangumi Access Token',type:'password'}]},
  {id:'network',label:'网络代理',icon:Network,providers:['mikan'],fields:[{key:'proxy_url',label:'代理地址'},{key:'proxy_bangumi_enabled',label:'Bangumi 使用代理',type:'boolean'},{key:'proxy_mikan_enabled',label:'Mikan 使用代理',type:'boolean'},{key:'proxy_tmdb_enabled',label:'TMDB 使用代理',type:'boolean'},{key:'proxy_anilist_enabled',label:'AniList 使用代理',type:'boolean'},{key:'proxy_jellyfin_enabled',label:'Jellyfin 使用代理',type:'boolean'},{key:'proxy_ai_enabled',label:'AI 服务使用代理',type:'boolean'},{key:'proxy_updater_enabled',label:'应用更新使用代理',type:'boolean'}]},
  {id:'media',label:'媒体服务',icon:Film,providers:['jellyfin'],fields:[{key:'jellyfin_url',label:'Jellyfin 地址'},{key:'jellyfin_username',label:'用户名'},{key:'jellyfin_password',label:'密码',type:'password'},{key:'jellyfin_api_key',label:'API Key',type:'password'},{key:'alist_url',label:'AList 地址'},{key:'alist_token',label:'AList Token',type:'password'}]},
  {id:'ai',label:'AI 助手',icon:Bot,fields:[{key:'ai_base_url',label:'Base URL'},{key:'ai_model',label:'模型'},{key:'ai_api_key',label:'API Key',type:'password'}]},
  {id:'cloud',label:'云备份',icon:Cloud,fields:[{key:'r2_endpoint',label:'R2 Endpoint'},{key:'r2_bucket',label:'Bucket'},{key:'r2_access_key',label:'Access Key',type:'password'},{key:'r2_secret_key',label:'Secret Key',type:'password'}]},
  {id:'security',label:'安全与外观',icon:ShieldCheck,fields:[]},
  {id:'maintenance',label:'应用维护',icon:Wrench,fields:[]},
]
const ui=useUIStore(),qc=useQueryClient(),actions=useAsyncActions(),active=ref('downloader'),form=reactive<Record<string,string>>({}),connection=reactive<Record<string,{connected:boolean;detail:string;account?:string}|null>>({}),oldPassword=ref(''),newPassword=ref(''),confirmPassword=ref(''),models=ref<string[]>([])
const query=useQuery({queryKey:['settings'],queryFn:()=>api<SettingsData>('/settings')})
const audits=useQuery({queryKey:['audit-logs'],queryFn:()=>api<{items:AuditEntry[]}>('/audit-logs?page_size=25')})
const maintenance=useQuery({queryKey:['maintenance'],queryFn:()=>api<Record<string,unknown>>('/settings/maintenance'),refetchInterval:15000})
watchEffect(()=>{if(query.data.value)Object.assign(form,query.data.value.values)})
const group=computed(()=>groups.find(g=>g.id===active.value)||groups[0])
const isSecret=(field:Field)=>field.type==='password'
const fieldPlaceholder=(field:Field)=>field.key==='proxy_url'?'例如 http://127.0.0.1:7890 或 socks5://127.0.0.1:7890':isSecret(field)&&query.data.value?.configured[field.key]?'已配置；留空表示保持不变':''
async function save(){try{await actions.run('save',async()=>{await api('/settings',{method:'PUT',body:JSON.stringify({values:form}),headers:{'Content-Type':'application/json'}});ui.toast('设置已保存并同步到本地 config.yaml');qc.invalidateQueries({queryKey:['settings']})})}catch(e){ui.toast(e instanceof Error?e.message:'保存失败','error')}}
async function testProvider(provider:string){connection[provider]=null;try{await actions.run(`provider-${provider}`,async()=>{connection[provider]=await api(`/settings/connections/${provider}`)})}catch(e){connection[provider]={connected:false,detail:e instanceof Error?e.message:'连接失败'}}}
async function testProxy(){connection.proxy=null;try{await actions.run('test-proxy',async()=>{connection.proxy=await api('/settings/proxy/test',{method:'POST',body:JSON.stringify({proxy_url:form.proxy_url||''}),headers:{'Content-Type':'application/json'}})})}catch(e){connection.proxy={connected:false,detail:e instanceof Error?e.message:'代理连接失败'}}}
async function testR2(){connection.r2=null;try{await actions.run('test-r2',async()=>{const result=await api<{message?:string}>('/backup/r2/test',{method:'POST',body:JSON.stringify({endpoint:form.r2_endpoint||'',bucket:form.r2_bucket||'',access_key:form.r2_access_key||'',secret_key:form.r2_secret_key||''}),headers:{'Content-Type':'application/json'}});connection.r2={connected:true,detail:result.message||'读写校验通过'}})}catch(e){connection.r2={connected:false,detail:e instanceof Error?e.message:'连接失败'}}}
async function loadModels(){try{await actions.run('load-models',async()=>{const result=await api<{models:string[]}>(`/settings/ai/models?base_url=${encodeURIComponent(form.ai_base_url||'')}`);models.value=result.models||[];ui.toast(models.value.length?`找到 ${models.value.length} 个模型`:'没有返回可用模型','info')})}catch(e){ui.toast(e instanceof Error?e.message:'模型列表加载失败','error')}}
async function changePassword(){if(newPassword.value.length<8||newPassword.value!==confirmPassword.value){ui.toast('新密码至少 8 位，且两次输入必须一致','error');return}try{await actions.run('change-password',async()=>{await api('/session/change-password',{method:'POST',body:JSON.stringify({old_password:oldPassword.value,new_password:newPassword.value}),headers:{'Content-Type':'application/json'}});oldPassword.value='';newPassword.value='';confirmPassword.value='';ui.toast('密码修改成功');qc.invalidateQueries({queryKey:['audit-logs']})})}catch(e){ui.toast(e instanceof Error?e.message:'密码修改失败','error')}}
async function updateAction(action:'check'|'apply'){try{await actions.runTask(`update-${action}`,()=>api<TaskAccepted>(`/settings/updater/${action}`,{method:'POST'}),action==='check'?'检查应用更新':'下载并应用更新','updater');ui.toast(action==='check'?'更新检查已经启动':'更新下载与应用已经启动')}catch(e){ui.toast(e instanceof Error?e.message:'更新操作失败','error')}}
const deploymentItems=computed(()=>{const d=maintenance.data.value?.deployment as Record<string,unknown>|undefined;return (d?.Items||d?.items||[]) as Array<Record<string,unknown>>})
const updater=computed(()=>(maintenance.data.value?.updater||{}) as Record<string,unknown>)
</script>

<template><div class="page-grid"><PageHeader eyebrow="PREFERENCES" title="系统设置" description="按任务分组配置下载、元数据、媒体服务、AI、安全和应用维护。"><AsyncButton v-if="group.fields.length" class="btn btn-primary" :loading="actions.isBusy('save')" loading-label="正在保存…" @click="save"><Save :size="17"/>保存更改</AsyncButton></PageHeader><StateBlock v-if="query.isLoading.value" state="loading"/><StateBlock v-else-if="query.isError.value" state="error" title="设置加载失败" :retrying="query.isFetching.value" @retry="query.refetch()"/><section v-else class="grid gap-5 lg:grid-cols-[250px_1fr]"><nav class="panel h-fit p-3" aria-label="设置分组"><button v-for="item in groups" :key="item.id" class="mb-1 flex min-h-12 w-full items-center gap-3 rounded-xl px-3 text-left font-bold" :class="active===item.id?'bg-[var(--brand-soft)] text-[var(--brand-strong)]':'muted hover:bg-[var(--surface-muted)]'" @click="active=item.id"><component :is="item.icon" :size="18"/>{{ item.label }}</button></nav><article class="panel min-w-0 p-5 sm:p-7"><div class="mb-6 flex items-center gap-3"><span class="grid h-11 w-11 place-items-center rounded-xl bg-[var(--brand-soft)] text-[var(--brand)]"><component :is="group.icon"/></span><div><p class="eyebrow">CONFIGURATION</p><h3 class="text-2xl font-black">{{ group.label }}</h3></div></div>
  <template v-if="group.fields.length">
    <div class="grid gap-5 md:grid-cols-2"><label v-for="field in group.fields" :key="field.key" class="label" :class="field.type==='boolean'?'panel-muted flex min-h-14 grid-cols-[1fr_auto] items-center px-4':''">{{ field.label }}<select v-if="field.type==='select'" v-model="form[field.key]" class="field"><option v-for="option in field.options" :key="option.value" :value="option.value">{{ option.label }}</option></select><input v-else-if="field.type==='boolean'" :checked="form[field.key]==='true'" type="checkbox" class="h-5 w-5 accent-[var(--brand)]" @change="form[field.key]=($event.target as HTMLInputElement).checked?'true':'false'"/><input v-else v-model="form[field.key]" class="field" :type="isSecret(field)?'password':'text'" :autocomplete="isSecret(field)?'new-password':'off'" :data-1p-ignore="isSecret(field)?'true':undefined" :placeholder="fieldPlaceholder(field)"/><span v-if="isSecret(field)&&query.data.value?.configured[field.key]" class="flex items-center gap-1 text-xs font-normal text-[var(--success)]"><KeyRound :size="12"/>凭据已安全保存</span></label></div>
    <div v-if="group.id==='network'" class="panel-muted mt-6 flex items-start gap-3 p-4 text-sm leading-6 muted"><Network class="mt-1 shrink-0 text-[var(--sky)]" :size="18"/>只填主机和端口时会自动按 HTTP 代理保存。代理运行在另一台设备时，请填写其局域网地址并在代理软件中允许局域网连接；每项开关只影响对应服务。</div>
    <div class="panel-muted mt-6 flex items-start gap-3 p-4 text-sm leading-6 muted"><Settings2 class="mt-1 shrink-0 text-[var(--sky)]" :size="18"/>敏感字段不会从服务器回传。密码框留空时保留原值，填写新值时才会覆盖。保存后，系统配置也会同步到本地 config.yaml；该文件可能包含服务密钥，请勿分享。</div>
    <AsyncButton v-if="group.id==='network'" class="panel-muted mt-6 min-h-20 w-full p-3 text-left" :loading="actions.isBusy('test-proxy')" loading-label="代理测试中…" @click="testProxy"><div class="flex items-center justify-between"><strong>测试当前代理地址</strong><RefreshCw :size="15" class="text-[var(--sky)]"/></div><p class="mt-2 text-xs" :class="connection.proxy?.connected?'text-[var(--success)]':'muted'">{{ connection.proxy?(connection.proxy.connected?'代理连接成功':connection.proxy.detail):'使用当前输入值访问 Bangumi 测试目标，无需先保存' }}</p></AsyncButton>
    <div v-if="group.providers?.length" class="mt-6"><h4 class="font-black">连接状态</h4><div class="mt-3 grid gap-3 sm:grid-cols-2"><AsyncButton v-for="provider in group.providers" :key="provider" class="panel-muted min-h-20 p-3 text-left" :loading="actions.isBusy(`provider-${provider}`)" loading-label="连接测试中…" @click="testProvider(provider)"><div class="flex items-center justify-between"><strong class="uppercase">{{ provider }}</strong><RefreshCw :size="15" class="text-[var(--sky)]"/></div><p class="mt-2 text-xs" :class="connection[provider]?.connected?'text-[var(--success)]':'muted'">{{ connection[provider]?(connection[provider]?.connected?`已连接 ${connection[provider]?.account||''}`:connection[provider]?.detail):'点击测试当前已保存配置' }}</p></AsyncButton></div></div>
    <AsyncButton v-if="group.id==='cloud'" class="panel-muted mt-6 min-h-20 w-full p-3 text-left" :loading="actions.isBusy('test-r2')" loading-label="R2 测试中…" @click="testR2"><div class="flex items-center justify-between"><strong>R2 读写连通性</strong><RefreshCw :size="15" class="text-[var(--sky)]"/></div><p class="mt-2 text-xs" :class="connection.r2?.connected?'text-[var(--success)]':'muted'">{{ connection.r2?.detail||'点击测试表单中的配置；空白凭据沿用已保存值' }}</p></AsyncButton>
    <AsyncButton v-if="group.id==='ai'" class="btn btn-secondary mt-5" :loading="actions.isBusy('load-models')" loading-label="读取中…" @click="loadModels"><RefreshCw :size="16"/>读取模型列表</AsyncButton><div v-if="models.length" class="mt-3 flex flex-wrap gap-2"><button v-for="model in models" :key="model" class="badge" @click="form.ai_model=model">{{ model }}</button></div>
  </template>
  <template v-else-if="group.id==='security'"><div class="grid gap-6 xl:grid-cols-2"><section><h4 class="font-black">外观与辅助功能</h4><label class="label mt-4">主题模式<select class="field" :value="ui.theme" @change="ui.setTheme(($event.target as HTMLSelectElement).value as ThemeMode)"><option value="system">跟随系统</option><option value="light">亮色</option><option value="dark">深色</option></select></label><div class="panel-muted mt-4 p-4"><ShieldCheck class="text-[var(--success)]"/><h4 class="mt-3 font-extrabold">浏览器安全策略已启用</h4><p class="muted mt-1 text-sm leading-6">会话 Cookie、同源写保护、本机恢复限制与审计记录由服务器统一执行。</p></div></section><section><h4 class="font-black">修改管理员密码</h4><div class="mt-4 grid gap-3"><input v-model="oldPassword" class="field" type="password" placeholder="当前密码"/><input v-model="newPassword" class="field" type="password" placeholder="新密码（至少 8 位）"/><input v-model="confirmPassword" class="field" type="password" placeholder="再次输入新密码"/><AsyncButton class="btn btn-primary" :loading="actions.isBusy('change-password')" loading-label="修改中…" @click="changePassword"><KeyRound :size="16"/>修改密码</AsyncButton><RouterLink to="/recover" class="btn btn-secondary">打开本机恢复</RouterLink></div></section></div><section class="mt-8"><div class="flex items-center justify-between"><h4 class="font-black">最近安全审计</h4><AsyncButton class="btn btn-quiet" :loading="audits.isFetching.value" loading-label="刷新中…" @click="audits.refetch()"><RefreshCw :size="15"/>刷新</AsyncButton></div><div class="mt-3 overflow-x-auto"><table class="w-full min-w-[680px] text-left text-sm"><thead class="muted"><tr><th class="p-3">时间</th><th class="p-3">账户</th><th class="p-3">操作</th><th class="p-3">结果</th><th class="p-3">来源</th></tr></thead><tbody><tr v-for="entry in audits.data.value?.items||[]" :key="entry.id" class="border-t border-[var(--line)]"><td class="p-3">{{ new Date(entry.created_at).toLocaleString() }}</td><td class="p-3">{{ entry.username||'系统' }}</td><td class="p-3 font-bold">{{ entry.action }}</td><td class="p-3"><span class="badge" :class="entry.outcome==='success'?'badge-success':'badge-danger'">{{ entry.outcome }}</span></td><td class="p-3 muted">{{ entry.ip }}</td></tr></tbody></table></div></section></template>
  <template v-else><section class="panel-muted p-4"><h4 class="font-black">版本更新</h4><p class="muted mt-2 text-sm">{{ updater.LastMessage||updater.last_message||'更新服务尚未运行' }}</p><div class="mt-3 flex flex-wrap gap-2"><span class="badge">当前 {{ updater.CurrentVersion||updater.current_version||'未知' }}</span><span v-if="updater.LatestVersion||updater.latest_version" class="badge badge-success">最新 {{ updater.LatestVersion||updater.latest_version }}</span></div><div class="mt-4 flex flex-wrap gap-2"><AsyncButton class="btn btn-secondary" :loading="actions.isBusy('update-check','repo-update-check')" loading-label="检查中…" @click="updateAction('check')"><RefreshCw :size="16"/>立即检查</AsyncButton><AsyncButton class="btn btn-primary" :disabled="!(updater.HasUpdate||updater.has_update)" :loading="actions.isBusy('update-apply','repo-update-apply')" loading-label="更新中…" @click="updateAction('apply')">下载并应用更新</AsyncButton></div></section><section class="mt-6"><h4 class="font-black">部署检查</h4><div class="mt-3 grid gap-3"><article v-for="(item,i) in deploymentItems" :key="i" class="panel-muted p-4"><div class="flex items-center justify-between gap-3"><strong>{{ item.Name||item.name }}</strong><span class="badge" :class="(item.Status||item.status)==='pass'?'badge-success':(item.Status||item.status)==='fail'?'badge-danger':'badge-warning'">{{ item.Status||item.status }}</span></div><p class="muted mt-2 text-sm">{{ item.Summary||item.summary }}</p><p v-if="item.Action||item.action" class="mt-2 text-sm text-[var(--warning)]">{{ item.Action||item.action }}</p></article></div></section></template>
  </article></section></div></template>
