<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { useQuery, useQueryClient } from '@tanstack/vue-query'
import { CircleAlert, Clock3, FilePenLine, Filter, History, Pause, Play, Plus, RefreshCw, Search, Sparkles, Trash2, Upload } from '@lucide/vue'
import { api, handlePosterError, posterURL } from '../api/client'
import type { MikanSubscriptionSelection, Subscription, TaskAccepted } from '../api/types'
import AppDialog from '../components/AppDialog.vue'
import AsyncButton from '../components/AsyncButton.vue'
import ConfirmDialog from '../components/ConfirmDialog.vue'
import MikanDiscoveryDialog from '../components/MikanDiscoveryDialog.vue'
import PageHeader from '../components/PageHeader.vue'
import StateBlock from '../components/StateBlock.vue'
import { useAsyncActions } from '../composables/useAsyncActions'
import { useUIStore } from '../stores/ui'
import { switchToMikanAggregate } from '../utils/mikanSubscription'

interface Payload { items: Subscription[]; trend: { checked_count:number; success_count:number; warning_count:number; error_count:number; active_issue_count:number }; scheduler: { is_running?:boolean; last_summary?:string } }
interface Validation { primary_count:number; backup_count?:number; matching_count:number; warnings?:string[]; preview_titles?:string[]; using_backup_hint?:string }
interface HistoryData { Subscription: Subscription; Runs:Array<Record<string,unknown>>; Logs:Array<Record<string,unknown>> }
type Mode = 'form' | 'batch' | null

const ui=useUIStore(), qc=useQueryClient(), actions=useAsyncActions(), search=ref(''), filter=ref('all'), mode=ref<Mode>(null), discoveryOpen=ref(false), resumeFormAfterDiscovery=ref(false), deleteTarget=ref<Subscription|null>(null), detailTarget=ref<Subscription|null>(null), editing=ref<Subscription|null>(null)
const form=reactive({title:'',rss_url:'',backup_rss_url:'',mikan_id:'',image:'',subtitle_group:'',season:'',filter_rule:'',exclude_rule:'',expected_episodes:0,allow_multi_subgroup:false,auto_disable_on_done:false,stale_after_hours:168})
const validation=ref<Validation|null>(null), batchText=ref(''), batchPreview=ref<Array<Record<string,unknown>>>([])
const query=useQuery({queryKey:['subscriptions'],queryFn:()=>api<Payload>('/subscriptions')})
const history=useQuery({queryKey:computed(()=>['subscription-history',detailTarget.value?.ID]),queryFn:()=>api<HistoryData>(`/subscriptions/${detailTarget.value!.ID}/history`),enabled:computed(()=>Boolean(detailTarget.value))})
const items=computed(()=>{const list=query.data.value?.items||[];return list.filter(item=>{const text=`${item.title} ${item.subtitle_group||''}`.toLowerCase();const matches=text.includes(search.value.toLowerCase());const state=filter.value==='all'||(filter.value==='active'&&item.is_active)||(filter.value==='paused'&&!item.is_active)||(filter.value==='issues'&&(Boolean(item.last_error_display)||item.has_repair_actions));return matches&&state})})
const batchItems=computed(()=>batchText.value.split('\n').map(line=>line.trim()).filter(Boolean).map(line=>{const [title,rss_url,filter_rule='']=line.split('|').map(v=>v.trim());return{title,rss_url,filter_rule}}).filter(item=>item.title&&item.rss_url))
function resetForm(){Object.assign(form,{title:'',rss_url:'',backup_rss_url:'',mikan_id:'',image:'',subtitle_group:'',season:'',filter_rule:'',exclude_rule:'',expected_episodes:0,allow_multi_subgroup:false,auto_disable_on_done:false,stale_after_hours:168});editing.value=null;validation.value=null}
function openCreate(){resetForm();mode.value='form'}
function openEdit(item:Subscription){editing.value=item;Object.assign(form,{title:item.title,rss_url:item.rss_url,backup_rss_url:item.backup_rss_url||'',mikan_id:item.mikan_id||'',image:item.image||'',subtitle_group:item.subtitle_group||'',season:item.season||'',filter_rule:item.filter_rule||'',exclude_rule:item.exclude_rule||'',expected_episodes:item.expected_episodes||0,allow_multi_subgroup:Boolean(item.allow_multi_subgroup),auto_disable_on_done:Boolean(item.auto_disable_on_done),stale_after_hours:item.stale_after_hours||168});validation.value=null;mode.value='form'}
function openDiscovery(fromForm=false){if(!fromForm)resetForm();resumeFormAfterDiscovery.value=fromForm;mode.value=null;discoveryOpen.value=true}
function setDiscoveryOpen(value:boolean){discoveryOpen.value=value;if(!value&&resumeFormAfterDiscovery.value){resumeFormAfterDiscovery.value=false;mode.value='form'}}
function applyMikanSelection(selection:MikanSubscriptionSelection){Object.assign(form,{mikan_id:selection.mikan_id,title:selection.title,image:selection.image,season:selection.season,subtitle_group:selection.subtitle_group,rss_url:selection.rss_url,backup_rss_url:selection.backup_rss_url,filter_rule:selection.filter_rule,allow_multi_subgroup:selection.allow_multi_subgroup});validation.value=null;resumeFormAfterDiscovery.value=false;discoveryOpen.value=false;mode.value='form'}
function handleMultiSubgroupChange(){switchToMikanAggregate(form);validation.value=null}
async function save(){try{await actions.run('save',async()=>{const path=editing.value?`/subscriptions/${editing.value.ID}`:'/subscriptions';await api(path,{method:editing.value?'PUT':'POST',body:JSON.stringify(form),headers:{'Content-Type':'application/json'}});ui.toast(editing.value?'订阅已保存':'订阅已添加');mode.value=null;resetForm();qc.invalidateQueries({queryKey:['subscriptions']})})}catch(e){ui.toast(e instanceof Error?e.message:'保存失败','error')}}
async function validate(){if(!form.rss_url)return;try{await actions.run('validate',async()=>{const params=new URLSearchParams({title:form.title,rss:form.rss_url,backup_rss:form.backup_rss_url,filter:form.filter_rule,exclude:form.exclude_rule,subtitle_group:form.subtitle_group,allow_multi_subgroup:String(form.allow_multi_subgroup)});validation.value=await api<Validation>(`/subscriptions/validate-rss?${params}`)})}catch(e){ui.toast(e instanceof Error?e.message:'RSS 校验失败','error')}}
async function operate(item:Subscription,name:string){try{if(name==='run')await actions.runTask(`run-${item.ID}`,()=>api<TaskAccepted>(`/subscriptions/${item.ID}/run`,{method:'POST'}),'订阅检查','subscription',`正在检查 ${item.title}`);else await actions.run(`toggle-${item.ID}`,()=>api(`/subscriptions/${item.ID}/toggle`,{method:'POST'}));ui.toast(name==='run'?'订阅检查已经启动':'订阅状态已更新');qc.invalidateQueries({queryKey:['subscriptions']})}catch(e){ui.toast(e instanceof Error?e.message:'操作失败','error')}}
async function repair(item:Subscription,name:string){try{await actions.runTask(`repair-${item.ID}-${name}`,()=>api<TaskAccepted>(`/subscriptions/${item.ID}/repair/${name}`,{method:'POST'}),'订阅修复','subscription-repair',`正在修复 ${item.title}`);ui.toast('修复任务已经启动')}catch(e){ui.toast(e instanceof Error?e.message:'修复失败','error')}}
async function remove(){if(!deleteTarget.value)return;const id=deleteTarget.value.ID;try{await actions.run(`remove-${id}`,async()=>{await api(`/subscriptions/${id}`,{method:'DELETE'});ui.toast('订阅已删除');deleteTarget.value=null;qc.invalidateQueries({queryKey:['subscriptions']})})}catch(e){ui.toast(e instanceof Error?e.message:'删除失败','error')}}
async function previewBatch(){if(!batchItems.value.length)return;try{await actions.run('batch-preview',async()=>{batchPreview.value=await api<Array<Record<string,unknown>>>('/subscriptions/batch-preview',{method:'POST',body:JSON.stringify(batchItems.value),headers:{'Content-Type':'application/json'}})})}catch(e){ui.toast(e instanceof Error?e.message:'预览失败','error')}}
async function importBatch(){try{await actions.run('batch-import',async()=>{const result=await api<{added:number;failed:number}>('/subscriptions/batch',{method:'POST',body:JSON.stringify(batchItems.value),headers:{'Content-Type':'application/json'}});ui.toast(`已添加 ${result.added} 条，失败 ${result.failed} 条`,result.failed?'info':'success');mode.value=null;batchText.value='';batchPreview.value=[];qc.invalidateQueries({queryKey:['subscriptions']})})}catch(e){ui.toast(e instanceof Error?e.message:'导入失败','error')}}
const field=(row:Record<string,unknown>,a:string,b:string)=>String(row[a]??row[b]??'')
const listLength=(row:Record<string,unknown>,a:string,b:string)=>{const value=row[a]??row[b];return Array.isArray(value)?value.length:0}
</script>

<template>
  <div class="page-grid">
    <PageHeader eyebrow="FOLLOW" title="订阅管理" description="从异常和新更新开始处理，让每一条 RSS 都保持可解释、可恢复。">
      <button class="btn btn-secondary" @click="openDiscovery()"><Sparkles :size="17"/>发现番剧</button>
      <button class="btn btn-secondary" @click="mode='batch'"><Upload :size="17"/>批量导入</button>
      <button class="btn btn-primary" @click="openCreate"><Plus :size="17"/>添加订阅</button>
    </PageHeader>
    <section v-if="query.data.value" class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><article v-for="item in [{label:'最近检查',value:query.data.value.trend.checked_count},{label:'成功',value:query.data.value.trend.success_count},{label:'关注',value:query.data.value.trend.warning_count},{label:'失败',value:query.data.value.trend.error_count},{label:'待处理',value:query.data.value.trend.active_issue_count}]" :key="item.label" class="panel p-4"><p class="muted text-xs font-bold">{{ item.label }}</p><strong class="mt-1 block text-2xl font-black">{{ item.value }}</strong></article></section>
    <section class="panel p-4"><div class="grid gap-3 md:grid-cols-[1fr_auto]"><label class="relative"><Search class="muted absolute left-3 top-3" :size="18"/><input v-model="search" class="field pl-10" placeholder="搜索番剧或字幕组" aria-label="搜索订阅"/></label><div class="flex gap-2 overflow-x-auto" aria-label="筛选订阅"><button v-for="item in [{id:'all',label:'全部'},{id:'active',label:'运行中'},{id:'paused',label:'已暂停'},{id:'issues',label:'有异常'}]" :key="item.id" class="btn whitespace-nowrap" :class="filter===item.id?'btn-primary':'btn-secondary'" @click="filter=item.id"><Filter v-if="item.id==='all'" :size="15"/>{{ item.label }}</button></div></div></section>
    <StateBlock v-if="query.isLoading.value" state="loading"/><StateBlock v-else-if="query.isError.value" state="error" title="订阅加载失败" :retrying="query.isFetching.value" @retry="query.refetch()"/><StateBlock v-else-if="!items.length" state="empty" title="没有符合条件的订阅" description="调整筛选条件，或添加第一条 RSS 订阅。"/>
    <section v-else class="grid gap-3">
      <article v-for="item in items" :key="item.ID" class="panel grid gap-4 p-4 md:grid-cols-[72px_1fr_auto] md:items-center">
        <img :src="posterURL(item.metadata||{image:item.image})" :alt="`${item.title} 海报`" loading="lazy" class="h-24 w-16 rounded-xl object-cover md:h-20 md:w-14" @error="handlePosterError($event,item.image)"/>
        <div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><h3 class="truncate font-extrabold">{{ item.metadata?.title_cn||item.metadata?.title||item.title }}</h3><span class="badge" :class="item.is_active?'badge-success':''">{{ item.is_active?'运行中':'已暂停' }}</span><span v-if="item.last_error_display||item.has_repair_actions" class="badge badge-danger"><CircleAlert :size="13"/>需处理</span></div><p class="muted mt-1 truncate text-sm">{{ item.subtitle_group||'未指定字幕组' }} · 已下载 {{ item.downloaded_count }}<span v-if="item.expected_episodes"> / {{ item.expected_episodes }}</span></p><p class="mt-2 text-xs" :class="item.last_error_display?'text-[var(--danger)]':'muted'">{{ item.last_error_display||item.last_run_summary||'等待首次检查' }}</p>
          <div v-if="item.has_repair_actions" class="mt-3 flex flex-wrap gap-2"><AsyncButton v-if="item.can_use_base_rss" class="badge badge-warning" :loading="actions.isBusy(`repair-${item.ID}-use-base-rss`,`subscription-${item.ID}-use-base-rss`)" loading-label="处理中…" @click="repair(item,'use-base-rss')">改用主 RSS</AsyncButton><AsyncButton v-if="item.can_clear_filter" class="badge badge-warning" :loading="actions.isBusy(`repair-${item.ID}-clear-filter`,`subscription-${item.ID}-clear-filter`)" loading-label="处理中…" @click="repair(item,'clear-filter')">清空过滤</AsyncButton><AsyncButton v-if="item.can_reset_stale_logs" class="badge badge-warning" :loading="actions.isBusy(`repair-${item.ID}-reset-logs`,`subscription-${item.ID}-reset-logs`)" loading-label="处理中…" @click="repair(item,'reset-logs')">清理阻塞记录</AsyncButton><AsyncButton v-if="item.can_retry_missing" class="badge badge-warning" :loading="actions.isBusy(`repair-${item.ID}-retry-missing`,`subscription-${item.ID}-retry-missing`)" loading-label="处理中…" @click="repair(item,'retry-missing')">重检缺集</AsyncButton><AsyncButton v-if="item.can_retry_stale" class="badge badge-warning" :loading="actions.isBusy(`repair-${item.ID}-recheck-stale`,`subscription-${item.ID}-recheck-stale`)" loading-label="处理中…" @click="repair(item,'recheck-stale')">重检停滞</AsyncButton><AsyncButton v-if="item.can_retry_upgrade" class="badge badge-warning" :loading="actions.isBusy(`repair-${item.ID}-retry-upgrade`,`subscription-${item.ID}-retry-upgrade`)" loading-label="处理中…" @click="repair(item,'retry-upgrade')">重试升级</AsyncButton><AsyncButton v-if="item.can_refresh_library" class="badge badge-warning" :loading="actions.isBusy(`repair-${item.ID}-refresh-library`,`subscription-${item.ID}-refresh-library`)" loading-label="处理中…" @click="repair(item,'refresh-library')">刷新媒体库</AsyncButton></div>
        </div>
        <div class="flex flex-wrap gap-2 md:justify-end"><AsyncButton class="btn btn-secondary" :loading="actions.isBusy(`toggle-${item.ID}`)" loading-label="处理中…" @click="operate(item,'toggle')"><Pause v-if="item.is_active" :size="16"/><Play v-else :size="16"/>{{ item.is_active?'暂停':'启用' }}</AsyncButton><AsyncButton class="btn btn-secondary" :loading="actions.isBusy(`run-${item.ID}`,`subscription-${item.ID}`)" loading-label="检查中…" @click="operate(item,'run')"><RefreshCw :size="16"/>检查</AsyncButton><button class="btn btn-quiet h-11 w-11 p-0" @click="detailTarget=item" aria-label="查看历史"><History :size="17"/></button><button class="btn btn-quiet h-11 w-11 p-0" @click="openEdit(item)" aria-label="编辑订阅"><FilePenLine :size="17"/></button><button class="btn btn-danger h-11 w-11 p-0" @click="deleteTarget=item" aria-label="删除订阅"><Trash2 :size="16"/></button></div>
      </article>
    </section>

    <AppDialog :open="mode==='form'" :title="editing?'编辑订阅':'添加订阅'" description="先校验 RSS 与过滤规则，再保存。" wide @update:open="v=>{if(!v){mode=null;resetForm()}}">
      <form @submit.prevent="save">
        <div class="panel-muted mb-5 flex flex-wrap items-center justify-between gap-3 p-4">
          <div><p class="eyebrow">MIKAN ASSOCIATION</p><strong class="mt-1 block">{{ form.mikan_id ? `已关联 Mikan #${form.mikan_id}` : '尚未关联 Mikan' }}</strong><p class="muted mt-1 text-xs">{{ form.subtitle_group || (form.mikan_id ? '全部字幕组' : '可继续手动填写 RSS') }}<span v-if="form.season"> · {{ form.season }}</span></p></div>
          <button type="button" class="btn btn-secondary" @click="openDiscovery(true)"><Sparkles :size="16"/>{{ form.mikan_id?'重新关联':'从 Mikan 选择' }}</button>
        </div>
        <div class="grid gap-4">
          <label class="label">番剧名称<input v-model="form.title" class="field" required/></label>
          <label class="label">主 RSS 地址<input v-model="form.rss_url" class="field" type="url" required/></label>
          <label class="label">备用 RSS 地址<input v-model="form.backup_rss_url" class="field" type="url"/></label>
          <div class="grid gap-4 sm:grid-cols-2"><label class="label">包含规则<input v-model="form.filter_rule" class="field"/></label><label class="label">排除规则<input v-model="form.exclude_rule" class="field"/></label></div>
          <div class="grid gap-4 sm:grid-cols-2"><label class="label">预期集数<input v-model.number="form.expected_episodes" class="field" type="number" min="0"/></label><label class="label">无更新提醒（小时）<input v-model.number="form.stale_after_hours" class="field" type="number" min="1"/></label></div>
          <label class="flex min-h-11 items-center gap-3 font-bold"><input v-model="form.allow_multi_subgroup" type="checkbox" class="h-4 w-4 accent-[var(--brand)]" @change="handleMultiSubgroupChange"/>允许多字幕组共存</label>
          <p v-if="form.allow_multi_subgroup&&form.mikan_id" class="muted -mt-2 text-xs">已使用聚合 RSS；字幕组自动过滤已关闭，自定义规则会保留。</p>
          <label class="flex min-h-11 items-center gap-3 font-bold"><input v-model="form.auto_disable_on_done" type="checkbox" class="h-4 w-4 accent-[var(--brand)]"/>完结后自动暂停</label>
        </div>
        <div v-if="validation" class="panel-muted mt-5 p-4 text-sm"><strong>RSS 中 {{ validation.primary_count }} 项，规则命中 {{ validation.matching_count }} 项</strong><ul v-if="validation.warnings?.length" class="mt-2 list-disc space-y-1 pl-5 text-[var(--warning)]"><li v-for="warning in validation.warnings" :key="warning">{{ warning }}</li></ul><p v-if="validation.preview_titles?.length" class="muted mt-2 line-clamp-3">{{ validation.preview_titles.join(' · ') }}</p></div>
        <div class="mt-7 flex flex-wrap justify-end gap-2"><AsyncButton class="btn btn-secondary" :loading="actions.isBusy('validate')" loading-label="校验中…" @click="validate">校验 RSS</AsyncButton><AsyncButton type="submit" class="btn btn-primary" :loading="actions.isBusy('save')" loading-label="正在保存…">保存订阅</AsyncButton></div>
      </form>
    </AppDialog>
    <AppDialog :open="mode==='batch'" title="批量导入订阅" description="每行使用“番剧名 | RSS 地址 | 可选过滤规则”。系统会先预览，不会直接写入。" wide @update:open="v=>{if(!v)mode=null}"><textarea v-model="batchText" class="field min-h-48 font-mono text-sm" placeholder="示例番剧 | https://example.com/rss | 1080p"></textarea><div v-if="batchPreview.length" class="mt-5 grid gap-2"><div v-for="(item,i) in batchPreview" :key="i" class="panel-muted p-3 text-sm"><strong>{{ field(item,'Title','title') }}</strong><p class="muted mt-1">{{ item.Error||item.error||`${listLength(item,'Episodes','episodes')} 项预览` }}</p></div></div><div class="mt-6 flex justify-end gap-2"><AsyncButton class="btn btn-secondary" :disabled="!batchItems.length" :loading="actions.isBusy('batch-preview')" loading-label="生成中…" @click="previewBatch">生成预览</AsyncButton><AsyncButton class="btn btn-primary" :disabled="!batchPreview.length" :loading="actions.isBusy('batch-import')" loading-label="导入中…" @click="importBatch">确认导入 {{ batchItems.length }} 条</AsyncButton></div></AppDialog>
    <MikanDiscoveryDialog :open="discoveryOpen" @update:open="setDiscoveryOpen" @select="applyMikanSelection" />
    <AppDialog :open="Boolean(detailTarget)" :title="detailTarget?.title||'订阅历史'" description="最近的检查、下载和错误记录。" wide @update:open="v=>{if(!v)detailTarget=null}"><StateBlock v-if="history.isLoading.value" state="loading"/><StateBlock v-else-if="history.isError.value" state="error" title="历史记录加载失败" :retrying="history.isFetching.value" @retry="history.refetch()"/><div v-else class="grid gap-5 lg:grid-cols-2"><section><h3 class="font-black">最近检查</h3><div class="mt-3 space-y-2"><article v-for="run in history.data.value?.Runs||[]" :key="field(run,'ID','id')" class="panel-muted p-3 text-sm"><div class="flex items-center justify-between gap-2"><strong>{{ field(run,'Status','status')||'已检查' }}</strong><span class="muted flex items-center gap-1 text-xs"><Clock3 :size="13"/>{{ field(run,'CheckedAt','checked_at') }}</span></div><p class="muted mt-1">{{ field(run,'Summary','summary')||field(run,'Error','error') }}</p></article></div></section><section><h3 class="font-black">最近下载</h3><div class="mt-3 space-y-2"><article v-for="log in history.data.value?.Logs||[]" :key="field(log,'ID','id')" class="panel-muted p-3 text-sm"><strong class="line-clamp-2">{{ field(log,'Title','title') }}</strong><p class="muted mt-1">第 {{ field(log,'Episode','episode')||'?' }} 集 · {{ field(log,'Status','status') }}</p></article></div></section></div></AppDialog>
    <ConfirmDialog :open="Boolean(deleteTarget)" danger :loading="Boolean(deleteTarget&&actions.isBusy(`remove-${deleteTarget.ID}`))" loading-label="删除中…" title="删除这条订阅？" :description="`会同时删除 ${deleteTarget?.title||''} 的下载记录，且无法撤销。`" confirm-label="确认删除" @update:open="v=>{if(!v)deleteTarget=null}" @confirm="remove"/>
  </div>
</template>
